sudo: required

env:
  global:
    - DOCKER_COMPOSE_VERSION: 1.8.1
  matrix:
    - TOOL: docker-compose

services:
  - docker

before_install:
  - docker-compose/.travis/setup.sh

script:
  - docker-compose/.travis/build.sh
