---
# This task will configure the deployed CouchDB instance.

- name: disable reduce limit on views
  uri:
    url: "{{ db_protocol }}://{{ db_host }}:{{ db_port }}/_config/query_server_config/reduce_limit"
    method: PUT
    body: >
        "false"
    body_format: json
    status_code: 200
    user: "{{ db_username }}"
    password: "{{ db_password }}"
    force_basic_auth: yes
